Update Scoping.md
ShieldedLabs/crosslink-deployment pull request #43
Opened 2024-11-21 18:29 UTC by zookoatshieldedlabs

new updated rationale section (includes Zancas's suggestion about energy efficiency)

2024-11-21 18:29 UTC, zookoatshieldedlabs commented
@shielded-nate please review

2024-11-21 19:15 UTC, shielded-nate requested changes
I have only one blocker on these changes, where I didn't understand something about "hybrid finality".

2024-11-21 19:15 UTC, shielded-nate commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
I don't understand this phrase:

> Hybrid finality provides a stronger kind of protection for users than pure-Proof-of-Stake finality

Crosslink finality _is_ pure PoS finality, isn't it? It provides the same assurance.

2024-11-21 19:59 UTC, zookoatshieldedlabs commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
Great question! I think Crosslink finality is actually stronger than the finality of the (pure Proof-of-Stake) "finality component" inside Crosslink. Because I think Crosslink's Proof-of-Work component makes the job of an attacker who wants to break finality much harder by adding a *non-reusable* cost. What do you think? And, once you agree with that (:-)) then would you please suggest a way to communicate it effectively? Thanks. :-)

2024-11-21 20:07 UTC, shielded-nate commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
Ah, so one way to break finality is to control $$>\frac{2}{3}$$ of stake and generate sufficient votes to finalize two conflicting blocks. In Crosslink that would _also_ require 2 times the number of trailing PoW blocks worth of PoW proofs, so this attack requires more time/cost with Crosslink than pure BFT. Is this the case you're considering?

 ```suggestion
* Hybrid finality provides a stronger kind of protection for users than pure-Proof-of-Stake finality, by requiring PoW mining in addition to the PoS protocol to finalize a block. This helps lay a secure foundation for future scalability improvements.
```

Hrm, now in my edit I'm less clear on the connection for future scalability.

2024-11-21 20:21 UTC, zookoatshieldedlabs commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
(Let's leave the "connection for future scalability" issue aside for now. It is listed in Open Questions as "The rationale says that this lays the foundation for scalability. How does it lay the foundation for scalability?" in https://docs.google.com/document/d/1GZYQgQdzL1-GNJLWmt5CbTFXo1nuufkL7-gg7az_M2Q/edit?tab=t.0 .)

2024-11-21 21:44 UTC, zookoatshieldedlabs commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
No, what you wrote in that comment isn't necessarily correct, because the additional cost to the attacker of the required PoW blocks may be offset by the savings to the attacker of Proof-of-Stake receiving less subsidy. That's the "sum of the two costs" way of analyzing it. We could write it as:

`Ct`: cost of successfully attacking Crosslink
`Cs`: cost of successfully attacking the Proof-of-Stake component of Crosslink
`Cw`: cost of successfully attacking the Proof-of-Work component of Crosslink

`Ct = Cs + Cw`

I'd like to argue that this equation is invalid! Because the two terms are not of comparable! This would seem like a strange argument to make, since the types of the two terms are both "costs" and costs are fungible. You can always pay less for one thing in order to pay more for another thing, so costs ought to always be comparable.

But, I'm arguing here that there is an irreconcilable difference between `Cs` and `Ct`, namely that `Cs` is a *reusable* cost. I mean, in the case of multiple victims (related but not identical to the cryptography concept of a "multi-target attack"). If the attacker successfully violates the finality of pure-Proof-of-Stake one time, he can re-use that capability any number of times. If the attacker successfully violates the finality of Proof-of-Work one time, he *cannot* re-used that capability for a second attack.

So, to attempt squeeze this into a mathematical equation...

`v: number of victims attacked`
`ε: a negligible cost (e.g. generating another digital signature using a signing key that you already have)`
`1: a non-negligible cost (e.g. finding a Proof-of-Work block satisfying the current difficulty factor)`

In Crosslink:

`Ct = Cs * (ε * v) + Cw * (1 * v)`

2024-11-21 21:49 UTC, zookoatshieldedlabs commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
P.S. Not to broaden this discussion, but to branch off for another discussion: I think there is another potential irreconcilable difference between the costs to an attacker of Proof-of-Stake and of Proof-of-Work, which is that the community can penalize an attack on Proof-of-Stake by chain-forking and refusing to accept the specific coins that participated in an attack, but it can't do that in response to an attack on Proof-of-Work -- the closest it could do is to chain-fork and change the Proof-of-Work mining algorithm, thus penalizing all miners equally -- both those who participated in the attack and those who served honorably and tried to stop the attack. Attacks on Proof-of-Stake are _attributable_ to specific coins. This community recourse in the face of an attack on Proof-of-Stake has actually happened at least once in the real world, when the STEEM community chain-forked STEEM (naming their new fork "HIVE"), and refused to accept Justin Sun's coins into HIVE, since those coins had been used in a governance attack.

2024-11-25 18:06 UTC, zookoatshieldedlabs commented
Nate: pls review.

2024-11-26 01:02 UTC, shielded-nate commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
Hm… I understand `Ct = Cs * (ε * v) + Cw * (1 * v)`, but I'm a bit confused by two other things you said:

# First Confusion: What Cost Means

When I say "cost" I intended to mean "real world cost", so there's no such thing as a "reusable cost" in my meaning of the word. This would be distinguished from "cost on a ledger" (where the ledger is the thing we're attacking, because that's seems to mix abstraction layers between real world costs and the protocol we're analyzing).

## Cost of PoS Multi-Spend Attack

With a vague notion of "real world cost" in mind, consider the cost to compromise a PoS protocol in this way:

1. Acquire control of $>\frac{2}{3}$ of the token.
2. Use that to equivocate in the protocol, producing $N$ different conflicting blocks that are all signed as final.
3. Use those $N$ blocks to trick $N$ targets in order to achieve an attacker goal (such as profit).

I would guess the cost of 1 is the lowest the attacker can pull off. Some examples: A. buy that many tokens (expensive), B. borrow that many tokens (much cheaper), C. hack enough validator keys (maybe cheapest?).

The cost of step 2 is basically 0, and the cost of step 3 is out-of-scope.

## Cost of PoW Multi-Spend Attack

Now let's use a similar analysis for an $N$-spend attack on PoW:

1. Generate $N$ chain suffixes that are sufficiently long for the attacks in 3.
2. Use those $N$ chain suffixes to attack $N$ targets. (Cost out of scope as above.)

The cost of 1 is the lowest the attacker can pull off. Examples: A. acquire $N$ times as much mining capacity as the public network, B. find a break in the work function, C. find an implementation bug in all PoW-validation code, ...

The cost of A seems to be the strength of PoW, because it requires $N$ times the number of targets of malicious chain suffixes, which takes either $N$ times the mining capacity or $N$ wall clock time where the world only gets $1/N$ or being $N$ times as lucky as all other miners.

# Confusion Two: PoS Subsidy

The other confusion (which maybe is resolved if Confusion One is resolved?) is:

> the additional cost to the attacker of the required PoW blocks may be offset by the savings to the attacker of Proof-of-Stake receiving less subsidy.

Is this something about opportunity costs? How is the attackers cost offset at all by the PoS subsidy?

In my thinking it is not altered by the PoS subsidy, because (if we assume no slashing) exactly one of the malicious histories becomes canonical and the other PoS histories cost ~0 to produce. Now if we try to account for slashing, it still doesn't seem like the subsidy is that important compared to the size of the bonded stake that can be slashed. So I am confused why PoS subsidy size comes into play.

OTOH, it's clear to me that PoW subsidy comes into play as an opportunity cost in the pure PoW attack, because when any wall clock time mining capacity spends is a "real world" cost, whether that's aimed at the "chain which will become canonical" or any other chain (including malicious chains) or even just sitting idle.

(All of this discussion ignores social slashing.)

2024-12-06 18:29 UTC, zookoatshieldedlabs commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
Okay, as far as your Confusion One, what you wrote there seems exactly right to me, so I'm going to reproduce it below and change its name from Confusion One to Clarification One:

> # Clarification One: What Cost Means
> When I say "cost" I intended to mean "real world cost", so there's no such thing as a "reusable cost" in my meaning of the word. This would be distinguished from "cost on a ledger" (where the ledger is the thing we're attacking, because that's seems to mix abstraction layers between real world costs and the protocol we're analyzing).
> 
> ## Cost of PoS Multi-Spend Attack
> With a vague notion of "real world cost" in mind, consider the cost to compromise a PoS protocol in this way:
> 
> 1. Acquire control of 
>      >
>      
>        2
>        3
>      
>     of the token.
> 2. Use that to equivocate in the protocol, producing 
>      N
>     different conflicting blocks that are all signed as final.
> 3. Use those 
>      N
>     blocks to trick 
>      N
>     targets in order to achieve an attacker goal (such as profit).
> 
> I would guess the cost of 1 is the lowest the attacker can pull off. Some examples: A. buy that many tokens (expensive), B. borrow that many tokens (much cheaper), C. hack enough validator keys (maybe cheapest?).
> 
> The cost of step 2 is basically 0, and the cost of step 3 is out-of-scope.
> 
> ## Cost of PoW Multi-Spend Attack
> Now let's use a similar analysis for an N -spend attack on PoW:
> 
> 1. Generate 
>      N
>     chain suffixes that are sufficiently long for the attacks in 3.
> 2. Use those 
>      N
>     chain suffixes to attack 
>      N
>     targets. (Cost out of scope as above.)
> 
> The cost of 1 is the lowest the attacker can pull off. Examples: A. acquire N times as much mining capacity as the public network, B. find a break in the work function, C. find an implementation bug in all PoW-validation code, ...
> 
> The cost of A seems to be the strength of PoW, because it requires N times the number of targets of malicious chain suffixes, which takes either N times the mining capacity or N wall clock time where the world only gets 1 / N or being N times as lucky as all other miners.

2024-12-06 18:31 UTC, zookoatshieldedlabs commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
As far as your Confusion Two, what I meant was that any ZEC issuance created by PoS stakers must mean that much less issuance created by PoW miners, and vice versa. So saying "Staking adds an additive cost to the attacker" has to be offset by how much *less* PoW difficulty there is for the attacker due to the issuance allocated to staking. Does that clear up your Confusion Two?

2024-12-06 18:52 UTC, shielded-nate commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
In discussion we distilled that previous paragraph to a few security analysis principles:

- it is invalid for security analysis to assume Crosslink deployment does not influence price.
- it is invalid for security analysis to assume Crosslink deployment will increase or decrease price.

We cannot predict influence on price reliably enough to use it for security assumptions, because a big enough change in price in either direction may invalidate any assumptions we make about price, and any security assumptions we predicated on that may become invalidated.

2024-12-06 19:00 UTC, zookoatshieldedlabs commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
Okay, that's a great point. We shouldn't rely on the assumption that deployment of Crosslink will be neutral on the price of ZEC, because that would lead to incorrect security arguments.

(For example, one might argue that deployment of Crosslink will result in reduced overall security compared to current 100% PoW, because the security of the PoW component of Crosslink, funded by part of the issuance of ZEC, plus the security of the PoS component of Crosslink, funded by the other part of the issuance of ZEC, would be less than the security of the current 100% PoW system. However, that argument would be incorrect if the deployment of Crosslink resulted in a higher price of ZEC which was sufficiently high to offset any such shortfall -- if it exists.)

On the other hand we shouldn't rely on the assumption that deployment of Crosslink _will_ change the price of ZEC, because we can't know that! Although we _do_ assert that [we believe deployment of Crosslink will increase demand and reduce on-the-market supply of ZEC](https://github.com/ShieldedLabs/crosslink-deployment/blob/34331a5e6bf6cb2ee44bf362cd016a44f95aedd8/Scoping.md?plain=1#L8). So maybe we should just rely on that for our security analysis. [🤔](https://emojipedia.org/thinking-face)

2024-12-06 19:02 UTC, shielded-nate commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
I believe it's fine to use an assertion about price for motivation but not for security analysis. It's okay to "bet" for motivations but very dangerous/risky to "bet" on security.

2024-12-06 19:08 UTC, shielded-nate commented on Scoping.md
> +* Proof-of-Work provides a different and complementary kind of security that Proof-of-Stake doesn’t: preventing attackers from re-using resources in attacks. Hybrid finality provides a stronger kind
Ok, I'm satisfied with the pull request, although some of this conversation needs to make it into some of our public documentation about "why we believe Crosslink is safe". (Tracked in #42 and #12 .)

2024-12-06 19:09 UTC, shielded-nate commented
I resolved a conversation with important dangling ideas that need to be captured in #42 and #12.

2024-12-06 19:09 UTC, merged